### ISSUE TITLE
how to set up?

### ISSUE THREAD

**Issue by yesnt01** [3e08488f9bcc2dd50192b3db89f6612c/SWF-Database#1]
Hi, I've been wanting to set up a transformice server for a long time. I came across your topic. Previously, I was able to set up a server in flash player times. But the system has changed a lot. I would be glad if you help me. I don't know where to start. and how to install without flash player support?  I am grateful in advance

**Comment by yesnt01** [comment]
after i run source, im getting this error 
<img width="647" alt="Ekran görüntüsü 2022-03-21 125704" src="https://user-images.githubusercontent.com/55454586/159238955-859e05f8-f9ca-45f1-b2fc-7738fa806ece.png">

**Comment by paranormalactivity22** [comment]
That source is python 2.7.10, download and install it from here https://www.python.org/downloads/release/python-2710/

Flash Player download from here -> 

Update: Adobe Flash’s latest version blocks any Flash content from running. Please uninstall latest version from your computer and install
[Windows] https://www.mediafire.com/file/3trqlquqskgzxnx/flashplayer28_0r0_161_winpep.msi/file
[Mac] https://www.mediafire.com/file/8wquua17pdike2y/flashplayer28_0r0_161_macpep_pkg.dmg/file
[Linux] https://www.mediafire.com/file/v6kahdvr9cv7xjr/flashplayer28_0r0_161_linuxpep.x86_64.tar.gz/file.

Also install zope interface, twisted, and lupa if source has lua support.

**Comment by yesnt01** [comment]
thank you but how can i edit swf? i want to set up my own server

**Comment by paranormalactivity22** [comment]
sothink swf decompiler for edit swf design

**Comment by yesnt01** [comment]
any tutorial?
