### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by neodouglas** [3e08488f9bcc2dd50192b3db89f6612c/SWF-Database#3]
poderia me passar um meio de contato seu? gostaria de pedir sua ajuda

**Comment by neodouglas** [comment]
queria saber se tu tinha algum tfmparser ou saberia me informar como eu faria isso, os que disponibiliza no topico não funcionam

**Comment by ghost** [comment]
solari s plz

**Comment by paranormalactivity22** [comment]
Paranormal Activity#6083 meu discord @neodouglas

**Comment by paranormalactivity22** [comment]
@lun4b0y never

**Comment by lun4b0y** [comment]
> @lun4b0y never

or else

**Comment by ghost** [comment]
> @lun4b0y never

fine
